name: Scrape latest needs

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  scheduled:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch latest JSON data
        run: |
          timestamp=$(date -u +"%Y-%m-%d")
          mkdir -p data
          curl https://www.givefood.org.uk/api/2/needs/ -o data/needs_${timestamp}.json

      - name: Extract and save today's data
        run: |
          timestamp=$(date -u +"%Y-%m-%d")
          mkdir -p data/daily
          jq --arg today "$timestamp" '.[] | select(.created | startswith($today))' data/needs_${timestamp}.json > data/daily/needs_${timestamp}.json

      - name: Commit and push if it changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Daily need data: ${timestamp}" || exit 0
          git push

